# Site settings
title: Hello Netlify
email: garcia.marc.a@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple site where I get to know what Netlify has to offer and how I 
  can help improve the team.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://digitalboba.com" # the base hostname & protocol for your site
twitter_username: tweetermarc
github_username:  marcagarcia

# Build settings
markdown: kramdown
